GoalsApp/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :goals
  resources :comments, only: [:new, :create, :destroy]

end

GoalsApp/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :commentable, polymorphic: true


end

GoalsApp/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end

end

GoalsApp/app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :user_id, :private_goal, presence: true


  has_many :comments, as: :commentable
  belongs_to :user
end

GoalsApp/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  attr_reader :password
  after_initialize :ensure_session_token
  has_many :goals

  has_many :comments, as: :commentable

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil if @user.nil?
    @user.is_password?(password) ? @user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

GoalsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def force_login
    redirect_to new_session_url if current_user.nil?
  end

  def skip_login
    redirect_to goals_url if current_user
  end
end

GoalsApp/app/controllers/comments_controller.rb
require "byebug"

class CommentsController < ApplicationController

  before_action :force_login
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    flash[:errors] = @comment.errors.full_messages
    # byebug
    if @comment.commentable_type == "User"
      redirect_to user_url(@comment.commentable_id)
    else
      redirect_to user_url(Goal.find(@comment.commentable_id).user.id)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    if @comment.commentable_type == "User"
      redirect_to user_url(@comment.commentable_id)
    else
      redirect_to user_url(Goal.find(@comment.commentable_id).user.id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end

end

GoalsApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :force_login

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_url
  end

  def index
    @goals = Goal.all
  end

  def goal_params
    params.require(:goal).permit(:title, :private_goal)
  end
end

GoalsApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :skip_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["Incorrect login info"]
      render :new
    end
  end

  def destroy
    logout_user
    redirect_to new_session_url
  end
end

GoalsApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :skip_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalsApp/app/helpers/comments_helper.rb
module CommentsHelper
end

GoalsApp/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalsApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

GoalsApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalsApp/app/views/goals/edit.html.erb
<h1>Edit Link</h1>

<%= render "layouts/errors" %>

<form action="<%= goal_url(@goal)%>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Title</label>
  <input type="text" name="goal[title]" id="Title" value="<%= @goal.title %>">
  <br>
  <label>private</label>
  <input type="radio" name="goal[private_goal]" id="private" value=<%= true %> <%= "checked" if @goal.private_goal %>>
  <br>
  <label>public</label>
  <input type="radio" name="goal[private_goal]" id="private" value=<%= false %>  <%= "checked" unless @goal.private_goal %>>

  <input type="submit" value="Update Goal">
</form>

GoalsApp/app/views/goals/index.html.erb
<h1>All Goals Index</h1>


<%= link_to "Create New Goal", new_goal_url %>

GoalsApp/app/views/goals/new.html.erb
<h1>Create Goal</h1>

<%= render "layouts/errors" %>

<form class="" action="/goals" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Title</label>
  <input type="text" name="goal[title]" id="Title">
  <br>
  <label>private</label>
  <input type="radio" name="goal[private_goal]" id="private" value="true">
  <br>
  <label>public</label>
  <input type="radio" name="goal[private_goal]" id="public" value="false">

  <input type="submit" value="Create Goal">
</form>

GoalsApp/app/views/goals/show.html.erb
<%= @goal.title %>


<%= link_to "Edit Goal", edit_goal_url(@goal) %>
<br>
  <%= render "layouts/errors" %>
<br>
<% @goal.comments.each do |comment| %>
  <%= comment.body %> <br>
  <%= button_to "Remove Comment", comment_url(comment), method: :delete %>
<% end %>

<br>
<label for="">Add Comment</label>
<form action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[commentable_id]" value="<%= @goal.id %>">
  <input type="hidden" name="comment[commentable_type]" value="Goal">

  <label for="">Comment</label>
  <input type="text" name="comment[body]" value="" id="Comment">

  <input type="submit" value="Add Comment">

</form>

GoalsApp/app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

GoalsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>

<%= yield %>

</body>
</html>

GoalsApp/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "layouts/errors" %>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="username">username</label>
  <input type="text" name="user[username]" id="username">
  <br>
  <label for="password">password</label>
  <input type="password" name="user[password]" id="password">
  <br>

  <input type="submit" value="Sign Up">
</form>

GoalsApp/app/views/users/show.html.erb
<%= @user.username %>


<br>
  <%= render "layouts/errors" %>
<br>
<label for="">User Comments</label>
<% @user.comments.each do |comment| %>
  <%= comment.body %> <br>
  <%= button_to "Remove Comment", comment_url(comment), method: :delete %>
<% end %>

<br>

<label for="">Goals and Goal Comments</label>
<% @user.goals.each do |goal| %>
  <% goal.comments.each do |comment| %>
  <br>
    <%= goal.title %>
    <%= comment.body %>
    <%= button_to "Remove Comment", comment_url(comment), method: :delete %>
  <% end %>
<% end %>

<form action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[commentable_id]" value="<%= @user.id %>">
  <input type="hidden" name="comment[commentable_type]" value="User">

  <label for="">Comment</label>
  <input type="text" name="comment[body]" value="" id= "Comment">

  <input type="submit" value="Add Comment">

</form>